### PR TITLE
Fix test suite

### PR DESCRIPTION
**Pull request by vlcinsky**
Trying to run test suite, some cases were failing.

PR is fixing these cases:
- detection of hg/git caused failure if some was missing
- trailing space in logs were removed by editor and caused failing case. Test modified to make the significant trailing space clearly visible and prone to removal by an editor.

### CODE REVIEW

**Comment by ekohl** [comment]
Apologies for not responding earlier. At first glance this looks good and a neat cleanup but Appveyor is still unhappy. Have you had a look at it?

**Comment by vlcinsky** [comment]
Reading logs form appveyor it looks, like following problems are present:
- console encoding: if console does not use utf-8, it might have problems to encode output of some chars to console and fails with that nasty encode problem error.
- problem to open a file: Windows typically locks the file used and other processes might have problems to access it. It reminds me the situation, when my "windows based" college cannot delete a file because it is already open in editor.
- attempt to write a stream to closed file: no idea what is going on.

As I do not have access to MS Windows, I am unable to investigate this easily.

 **Can some MS Windows user investigate the problems?** I guess running `$ tox` would serve the purpose (of course with proper investigation of what is going on).

**Comment by ekohl** [comment]
There is a `universal_newlines=True` in `subprocess that I think handles the encoding as well. Perhaps that would clean up the code enough?

**Comment by ekohl** [comment]
I forgot this was still open and created https://github.com/c4urself/bump2version/pull/27 as well. Given the Windows issues, should we even try to support it?

**Comment by jeremycarroll** [comment]
I [fixed](https://github.com/c4urself/bump2version/pull/33) the appveyor tests. They all seemed genuine bugs, and the fixes were in the code not the tests

**Comment by ekohl** [comment]
Closing in favor of the other PR

**Pull request closed without merging**
