### PR TITLE
add basic support for json files

### PR DESCRIPTION
**Pull request by kmohrf**
Hi,

this PR adds native support for JSON files and potentially other file formats that are easily serialized and expose a single root object. It’s especially helpful for projects that come with `package(-lock)?.json` files, where the simple regex-based version-replacement will sometimes inadvertently break dependency management.

The PR introduces a new configuration section type named `file+json` and a new optional property called `version_key`.

```ìni
[bumpversion:file+json:package.json]

[bumpversion:file+json:build.json]
version_key = packages.foo[2].bar
```

Configuration sections using the new `file+json` type will be handled as JSON files and when bump2version is asked to replace the version it will use the `version_key` property to locate the appropriate property in the file.

I didn’t add any tests yet in the hope that someone will provide some feedback first. I’ll gladly add them once this PR has some consensus.

### CODE REVIEW

**Comment by ekohl** [comment]
I like the general idea and design, but this is a rather large new feature. Like you said, it does need tests. A bit of bikeshedding: I'd move the classes to their own file.

The syntax also reminds me of https://stedolan.github.io/jq/ and I wonder what the connection/compatibility is.

**Comment by kmohrf** [comment]
I was hesitant to  create a new file because almost everything else resides in `__init__.py` too, but I second the feeling that it’s a little crowded in there :). I’ll gladly move this into a separate file.

The path syntax is basically JavaScript and I think that’s where jq got its inspiration from as well. That being said: I don’t think we need something that is compatible with jqs ridiculously extensive (but admittedly awesome) path expressions. The syntax as it is, is widely understood and intuitive for everyone who has worked with JSON.

I also thought about using a JSONPath library, but I think that is simply taking it too far. The only reason I ever wanted to have JSON support for is when bumpversion mistakenly changed the version of other packages in my package-lock.json thus breaking my release builds. People with even more complex needs are probably better served with configurable bumpversion hooks or something like that.

If you like the idea I will add some tests and will do some more cleanup. There is a [wishlist bug in the Debian tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916498) that asks for a switch from bumpversion to bump2version. I’d love to see this change in the coming debian release :).

**Comment by ekohl** [comment]
> I was hesitant to create a new file because almost everything else resides in `__init__.py`, but I second the feeling that it’s a little crowded in there

I think it's mostly historic, but there are already separate files present so we might as well go all the way :)

> If you like the idea I will add some tests and will do some more cleanup.

I'm certainly in favor of something like this. I could see people who want a similar backend for YAML or TOML so if you could make the mechanism suitable for extension that'd be a major benefit IMHO.

> There is a [wishlist bug in the Debian tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916498) that asks for a switch from bumpversion to bump2version.

Fedora has already switched so I'd certainly welcome Debian following suit :)

**Comment by c4urself** [comment]
> I was hesitant to create a new file because almost everything else resides in `__init__.py`, but I second the feeling that it’s a little crowded in there
> 
> I think it's mostly historic, but there are already separate files present so we might as well go all the way :)

Nice coincidence, I've created a PR for this here: https://github.com/c4urself/bump2version/pull/52
> 
> > If you like the idea I will add some tests and will do some more cleanup.
> 
> I'm certainly in favor of something like this. I could see people who want a similar backend for YAML or TOML so if you could make the mechanism suitable for extension that'd be a major benefit IMHO.

Fully agree.
> 
> > There is a [wishlist bug in the Debian tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916498) that asks for a switch from bumpversion to bump2version.
> 
> Fedora has already switched so I'd certainly welcome Debian following suit :)

👍

**Comment by kmohrf** [comment]
@ekohl if you plan on merging #52 any time soon I’ll rebase my PR on it. Any thoughts?

**Comment by c4urself** [comment]
We've just merged #52, you can rebase.

**Comment by kmohrf** [comment]
nice! good work @c4urself!

**Comment by florisla** [comment]
I'd prefer this to be named `[bumpversion:jsonfile:...]` or `structuredfile+json` to make it clear that this works differently versus `[bumpversion:file:...]`.

Apart from that, I'm not fully convinced yet that this should be in scope for bumpversion -- aren't there `npm` packages that do this?

Why would we support json and not XML, or YAML or TOML (if installed)?

**Comment by kmohrf** [comment]
I’ve looked at this a few days ago, but haven’t found the time to rebase/rework my branch yet.

> I'd prefer this to be named [bumpversion:jsonfile:...] or structuredfile+json to make it clear that this works differently versus [bumpversion:file:...].

I like the `+` syntax nice because it’s easy to discover the used format. However I don’t really care if there’s a `file` or `structuredfile` in front of it. So nay `jsonfile` and yay `structuredfile+json` as far as I’m concerned :).

> Why would we support json and not XML, or YAML or TOML (if installed)?

Because pretty much everyone uses JSON for dependency management files. At least that’s the reason, why I’m interested. Then again, there’s nothing stopping us from adding YAML and TOML support. As far as I can see the module interfaces match the one of the `json` module, so that should be pretty easy. There’s some work involved in detecting the proper formatting so we don’t generate overly large diffs.

> Apart from that, I'm not fully convinced yet that this should be in scope for bumpversion -- aren't there npm packages that do this?

npm itself does this. But bumpversion/bump2version is language agnostic whereas npm is tied to the node ecosystem. I work on a lot of projects that have a single codebase containing Python AND JavaScript sources. Quite often I have a `setup.py` and a `package.json`, a dedicated `VERSION` file and sometimes a few other places, that contain version strings and need to be updated in one go.

That being said, a hook-mechanism may be the better idea. This way it’d be easy to call `npm version ...` before bump2version creates commits and tags. Feel free to close this PR if you feel this is the better approach. I’ll gladly do the work once I find the time :).

**Comment by florisla** [comment]
Ideas:

Perhaps we can simply use `[bumpversion:file:...]` syntax and use the keywords below to see what structured lookup is desired.

    [bumpversion:file:version.json]
    opener: json
    expression: 
    indent: 4

The opener is loaded dynamically and could be `json` or `yaml` or `lazyxml` or ... whichever offers `load` and `dump`.

For the expression, why not use [glom](https://glom.readthedocs.io/)? It's like pythonic `jq` for Python objects.

Setting the value can be done with `glom.assign()`. https://glom.readthedocs.io/en/latest/api.html#target-mutation-with-assign-and-friends

**Comment by kmohrf** [comment]
I will not have the time to work on this in the near future and I think for my specific use-case (updating `package.json` and `package-lock.json` otherwise handled by npm) it would be more helpful to have some kind of command execution hook in bumpversion than structured file support.

**Pull request closed without merging**
