### PR TITLE
Corrected issues with the boolean operators in the config file being …

### PR DESCRIPTION
**Pull request by stampedeboss**
the added settings were not seen as valid, for instance, allow-dirty in the configuration file was treated as if it didn't exist since it was a still a string and not a Boolean.  I added the additional settings.

…treated as strings.

### CODE REVIEW

**Comment by florisla** [comment]
Hi, what was the result of `allow-dirty` being treated as if it didn't exist?
What's the desired behavior?

We should add a unit test which covers that behavior.

We also need to
- Fix failing continuous integration checks.
- Move the list of 'bool value name' options to a constant
- Drop the 'Bump version' commits in this branch

**Comment by stampedeboss** [comment]
It behaved like the parameter wasn’t present in the configuration file and errored out.

**Review by florisla — COMMENTED** [review]
What's going on here? The last commit reverses the first commit...

**Comment by florisla** [comment]
Hi, I've looked at this a bit.

What already works today in the config file is setting

    allow_dirty = True

What does not work (but shouldn't, because it's not uniform with other options such as `tag = True`):

    allow_dirty

And what also fails to work:

    allow_dirty = False

Your change does fix that last case.

I'm going to incorporate that and package it up with some unit tests.

**Comment by florisla** [comment]
@stampedeboss, please see #183 which incorporates your fix.

If you desire the 'automatic commit dirty files' as a feature (from https://github.com/c4urself/bump2version/pull/180/commits/579f21ce61f67aabea55aa70415712c5ec4bdfdb), please open a separate issue for that -- as that would require some discussion.

**Pull request closed without merging**
