### PR TITLE
support new lines

### PR DESCRIPTION
**Pull request by sharksforarms**
Fixes https://github.com/c4urself/bump2version/issues/13

### CODE REVIEW

**Comment by sharksforarms** [comment]
This would be possible with the current version, the problem lies on the `serialize =` parameter as it can accept multiple options (each option on a new line). This prevents having multi-line serialization

**Comment by sharksforarms** [comment]
Hey @ekohl , let me know if that's enough! Thanks for the quick reply, we're looking to use this project at work once this is a feature.

**Comment by c4urself** [comment]
Nope, need to check that out. Real busy at work wrapping up Q2 ATM though...

**Comment by sharksforarms** [comment]
@c4urself @ekohl Is travis needed to merge and release?

**Comment by sharksforarms** [comment]
@c4urself I can try and setup the travis if you want?

**Comment by c4urself** [comment]
@sharksforarms that'd be great, go for it

**Comment by sharksforarms** [comment]
https://travis-ci.org/sharksforarms/bump2version/builds/358647950

Ok yeah, I think we have to do a bit of work fixing these test cases, I'll take a look

**Comment by sharksforarms** [comment]
See https://github.com/c4urself/bump2version/pull/14
First time using travis, was as simple as logging in using github and activating the repo! Not bad! 👍 

https://travis-ci.org/sharksforarms/bump2version/builds/358662223

**Pull request merged**
