### PR TITLE
Prefer the shortest required pattern for version

### PR DESCRIPTION
**Pull request by fizyk**

### CODE REVIEW

**Comment by fizyk** [comment]
This pull request fixes #166

**Comment by fizyk** [comment]
@ekohl any thoughts on this?

**Review by florisla — CHANGES_REQUESTED** [review]
Looks good,

Can you integrate the changes I put in a merge request on your branch?

**Comment by fizyk** [comment]
@florisla sure, I simply merged it. Let me know if I should address anything else in the pull request.

**Review by florisla — APPROVED** [review]

**Pull request merged**
