### PR TITLE
adding semantic version example

### PR DESCRIPTION
**Pull request by miraculixx**
This adds an example that implements the semantic versioning flow

``` 
1.0.0 => 1.0.1-dev1 => 1.0.1-dev2 = > 1.0.1-rc1 => 1.0.1-rc2 => 1.0.1
         patch         build          release      build        release
```

credits to @jeremycarroll who provided the [crucial ideas](https://github.com/c4urself/bump2version/issues/29#issuecomment-416795198)

### CODE REVIEW

**Comment by florisla** [comment]
Look good to me!

This introduces an `examples` folder.  I think that makes sense -- the README is way too long as it is already.
I think in due time we should put some documentation up on ReadTheDocs.org.

I prefer adding this to /docs/examples/semantic instead of /examples/semantic .

**Comment by c4urself** [comment]
Yeah I really like the examples idea, I'd been thinking of doing something similar like an examples directory for various use-cases.

**Review by florisla — APPROVED** [review]

**Comment by florisla** [comment]
Hi, could you merge my proposed changes into your branch?

**Comment by miraculixx** [comment]
Done @florisla https://github.com/c4urself/bump2version/pull/177#issuecomment-757020860

**Pull request merged**
